Training:   0%|          | 0/1378 [00:00<?, ?it/s]Load data info from datainfo/train_df_t000102050810_v040607_pNone_seq5x7_sample3.pickle
Number of samples in training dataset:  11031
Number of samples in validation dataset:  1485
==================================================
CUDA used.
Load model from:  models/t000102050810_v040607_im92x304_s5x7_b8_rnn1000_optAdam.model.train
Load optimizer from:  models/t000102050810_v040607_im92x304_s5x7_b8_rnn1000_optAdam.optimizer.train
Record loss in:  records/t000102050810_v040607_im92x304_s5x7_b8_rnn1000_optAdam.txt
HBox(children=(IntProgress(value=0, max=10), HTML(value='')))

Traceback (most recent call last):
  File "main.py", line 111, in <module>
    ls = M_deepvo.step(t_x, t_y, optimizer).data.cpu().numpy()
  File "/home/davidgogh96/DeepVO/model.py", line 128, in step
    loss.backward()
  File "/home/davidgogh96/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/davidgogh96/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: out of memory

